### PR TITLE
feat(graphql): clean up types

### PR DESCRIPTION
**Pull request by moreal**
This pull request removed some types moved to subcommand and moved a field into other query. Please see the commit messages and changes.

Also, it is related with #298 #323 #327 #367.

### CODE REVIEW

**Review by ipdae — COMMENTED** [review]
deleted queries re-added in other pr?

**Comment by moreal** [comment]
> deleted queries re-added in other pr?

What other PR you mean?

**Review by ipdae — APPROVED** [review]

**Comment by ipdae** [comment]
conflict some graphTypes

**Review by area363 — APPROVED** [review]

**Comment by area363** [comment]
Can you take care of the conflicts? 🙏

**Comment by moreal** [comment]
> 
> 
> Can you take care of the conflicts? 🙏

I resolved it, thanks 🙏🏻

**Pull request merged**
