### PR TITLE
add workflow dispatch trigger to build and push step

### PR DESCRIPTION
**Pull request by sky1045**
image
Add github action trigger to simply build and push docker image

### CODE REVIEW

**Review by moreal — COMMENTED** [review]
It seems not to implement custom docker image tag feature yet. Is it intended?

**Comment by sky1045** [comment]
@moreal i recognized that after PR, working on it XD

**Review by moreal — APPROVED** [review]
Then it looks good to me.

**Review by Atralupus — APPROVED** [review]

**Comment by sky1045** [comment]
it can be tested only after merged to `development` branch. so if any problem occurs, i need to come back fix it ;)

**Pull request merged**
