### PR TITLE
Add Inventory.Items field

### PR DESCRIPTION
**Pull request by youngkiu**
When development is complete, I will register as a reviewer.
For the development record, I created a PR.

### CODE REVIEW

**Comment by youngkiu** [comment]
```
query {
  stateQuery {
    avatar(avatarAddress: "0x16741aa2387ad785d45D154293B7dC98C3A8e084") {
      name
      inventory {
        items(inventoryItemId : 700000) {
          count
          id
          itemType
        }
      }
    }
  }
}
```

```
{
  "data": {
    "stateQuery": {
      "avatar": {
        "name": "PoohVz",
        "inventory": {
          "items": [
            {
              "count": 98,
              "id": 700000,
              "itemType": "MATERIAL"
            }
          ]
        }
      }
    }
  },
  "extensions": {}
}
```

**Comment by youngkiu** [comment]
### Standard Example for Field Implementation
https://github.com/planetarium/NineChronicles.Headless/blob/development/NineChronicles.Headless/GraphTypes/StateQuery.cs#L22-L41

```
            Field<AvatarStateType>(
                name: "avatar",
                description: "State for avatar.",
                arguments: new QueryArguments(new QueryArgument<NonNullGraphType<AddressType>>
                {
                    Name = "avatarAddress",
                    Description = "Address of avatar."
                }),
                resolve: context =>
                {
                    var address = context.GetArgument<Address>("avatarAddress");
                    try
                    {
                        return context.Source.accountStateGetter.GetAvatarState(address);
                    }
                    catch (InvalidAddressException)
                    {
                        throw new InvalidOperationException($"The state {address} doesn't exists");
                    }
                });
```

There are many simple style implementations of the code above in the path below.
https://github.com/planetarium/NineChronicles.Headless/tree/development/NineChronicles.Headless/GraphTypes/States/Models/Item

**Comment by youngkiu** [comment]
I tried to be as similar to [EquipmentTypeTest.cs](https://github.com/planetarium/NineChronicles.Headless/blob/development/NineChronicles.Headless.Tests/GraphTypes/States/Models/EquipmentTypeTest.cs) as possible at Commit: f3a5b0c76e5a580e888782dc0d739bb3001d4b7e

**Comment by youngkiu** [comment]
I add medal item ID for unit test at https://github.com/planetarium/lib9c/pull/660

**Comment by youngkiu** [comment]
I tried to include https://github.com/planetarium/lib9c/pull/660 and use the medal ID (700000) in the Xunit test,
A compilation error occurred with the Lib9c development branch, so I request a review in the current state.

**Review by longfin — APPROVED** [review]

**Comment by youngkiu** [comment]
Headless' latest development branch includes https://github.com/planetarium/lib9c/pull/660 and changes the Xunit test to medal id (700000).

**Comment by youngkiu** [comment]
```bash
$ docker build . --tag planetariumhq/ninechronicles-headless:v100080-youngki-2021100501 --build-arg COMMIT=9a29d648c3e26035d07024a8bb3a1a30d0a80306
$ docker login  # Refer to 1Password.
$ docker push planetariumhq/ninechronicles-headless:v100080-youngki-2021100501
```

**Pull request merged**
