### PR TITLE
Add `shardedShop` in `stateQuery`.

### LINKED ISSUE #508: `shop` in `stateQuery` does not return all products in shop.
The `shop` state in `stateQuery` doesn't return all items in the shop. When using the query pasted in image below, it shows only a handful of listed items and most of them are low price items.

shop

### PR DESCRIPTION
**Pull request by AiOO**
Hi. I've faced the issue that the query `shop` does not returns any products. And I've been noticed that the `Shop` is not using any more and it's products are migrated to `ShardedShop` according to your working logs.

So I made a new query `shardedShop` to get products from `ShardedShop`. This query helps user get the `ShardedShop` they wants using parameters `itemSubType` and `nonce`. And I also added `ShopItemType.expiredBlockIndex` to know products' time to live.

@ipdae would you mind if I requested a review about this PR? I think this PR can resolve #508.

Thanks.

### CODE REVIEW

**Review by dahlia — COMMENTED** [review]
Could you rebase on the current _development_ branch?

@planetarium/9c-backend Please take a look.

**Comment by ipdae** [comment]
@AiOO @dahlia sorry for the late comment. I'm really sorry, but the shop query still doesn't work with changes in this PR. because shop has been changed to a structure related to 'SharedShopStateV2, Order' instead of 'ShardedShopState, ShopItem'.  could you please update the model?

**Comment by AiOO** [comment]
@ipdae @dahlia I appreciate for the detailed reply. I'll check intensively your comments and try to fix tonight. Thanks again! :D

**Comment by AiOO** [comment]
Hi, I'm sorry for late update. It took more time than I thought to figure out the changes.
I've changed to use `SharedShopStateV2` and `OrderDigest`. Please review it when you have time.

Thank you so much. :)

**Comment by dahlia** [comment]
Some tests apparently failed.  @ipdae Are they just flaky?

**Comment by ipdae** [comment]
@dahlia yes, maybe.

**Review by ipdae — APPROVED** [review]

**Comment by dahlia** [comment]
Thanks for your contribution.  It will be released in the release after next, probably v100103.

**Comment by AiOO** [comment]
Wow thank you 😆

**Pull request merged**
