### PR TITLE
test: reuse tests utilities from lib9c

### PR DESCRIPTION
**Pull request by moreal**
Before this pull request, the headless tests used copied implementations related to `TableSheets` from the past Lib9c. This occurred the implementation to be partitioned though their use-case is the same.

So this pull request makes the headless tests use the implementation from Lib9c as a reference project.

### CODE REVIEW

**Comment by area363** [comment]
https://github.com/planetarium/NineChronicles.Headless/runs/6210083432?check_suite_focus=true#step:5:6
I think there's a build error. Is this still a WIP?

**Comment by moreal** [comment]
> https://github.com/planetarium/NineChronicles.Headless/runs/6210083432?check_suite_focus=true#step:5:6 I think there's a build error. Is this still a WIP?

@area363 Oops, sorry for my mistake. I thought I updated this pull request's status to draft. As you said, this is WIP yet so I'll turn this pull request into draft status. Thanks!

**Comment by moreal** [comment]
I made this pull request pass the check build but it needs https://github.com/planetarium/lib9c/pull/969 PR merged.

**Comment by moreal** [comment]
Could you review this pull request @planetarium/9c-backend please?

**Review by ipdae — APPROVED** [review]

**Pull request merged**
