### PR TITLE
[Feature] ReplaySubject to Subject

### PR DESCRIPTION
**Pull request by Atralupus**
Close https://github.com/orgs/planetarium/projects/75

ReplaySubject -> Subject, and adjust preload test

### CODE REVIEW

**Review by moreal — APPROVED** [review]
🚀

**Comment by Atralupus** [comment]
> 🚀

Nono, it doesn't work

**Review by moreal — APPROVED** [review]

**Review by area363 — APPROVED** [review]
👏 Thank you!

**Comment by Atralupus** [comment]
Do not merge, it's not work

**Comment by moreal** [comment]
Is it okay to review now?

**Review by moreal — APPROVED** [review]

**Pull request merged**
