### PR TITLE
feat(cli): introduce `--no-reduce-store` option

### PR DESCRIPTION
**Pull request by moreal**
This pull request introduces a new option, `--no-reduce-store` to disable `ReduceStore` which doesn't store all updated states except for updated fungible assets. There is a case to want to use all updated states for debugging or services. This pull request is for them.

### CODE REVIEW

**Review by ipdae — COMMENTED** [review]
IMO, Renaming the option to `reducedStore` and keeping the default value false will helpful update convenience.

**Comment by moreal** [comment]
> IMO, Renaming the option to `reducedStore` and keeping the default value false will helpful update convenience.

But if the default value is `false` and `--reduced-store` is required to use reduced store, previous users will run without reduced store. I'm not sure about it 🤔

**Comment by moreal** [comment]
Is there no more opinions?

**Comment by moreal** [comment]
Thanks for rebasing this branch 🙏🏻  @area363.

If there is no disagreement, I hope this pull request is merged.

**Review by area363 — APPROVED** [review]
🚀

**Pull request merged**
