### PR TITLE
ci(gh-actions): build graphql schema automatically

### LINKED ISSUE #347: Build GraphQL schema file automatically
Since, the GraphQL schema documentation introduced, the `schema.graphql` file was also introduced and it is updated in manually for each pull request. It seems easy to mistake so it should be automated in CI (i.e. GitHub Actions).

### PR DESCRIPTION
**Pull request by moreal**
To resolve #347, this pull request does

- Provide the GraphQL schema as endpoint at `/schema.graphql`.
- Build the GraphQL schema automatically and it is used to generate document automatically. You can see the workflow execution history in https://github.com/moreal/NineChronicles.Headless/runs/2162549024
  - Also it deploys the schema at schema.graphql into GitHub Pages. You can see it in https://moreal.github.io/NineChronicles.Headless/schema.graphql.

### CODE REVIEW

**Comment by moreal** [comment]
PTAL @planetarium/9c-backend

**Review by area363 — APPROVED** [review]

**Review by ipdae — APPROVED** [review]
i think `graphql.schema`  can delete from this pr.

**Comment by moreal** [comment]
@ipdae What is the meaning of `graphql.schema` (maybe `schema.graphql`) to delete from this pull request? Is it to deploy `schema.graphql` into gh-pages branch or something other?

**Comment by ipdae** [comment]
i said we don't need version control from  [this](https://github.com/planetarium/NineChronicles.Headless/blob/development/schema.graphql) anymore. because the gh actions create the schema file.

**Comment by moreal** [comment]
@ipdae I removed the file in a195f7f, I will merge after the build successes.

**Pull request merged**
