### PR TITLE
bump lib9c

### PR DESCRIPTION
**Pull request by hskim881028**
SSIA

### CODE REVIEW

**Review by area363 — APPROVED** [review]

**Review by moreal — COMMENTED** [review]
I'm not sure but is it okay to target 94625edf600d36af06d4294c5ec9fe5a10378e18 instead of 38272c46835ba0ab2c7653f634795b5d23e7db45? There are changes like https://github.com/planetarium/lib9c/compare/94625edf600d36af06d4294c5ec9fe5a10378e18..38272c46835ba0ab2c7653f634795b5d23e7db45.

**Comment by hskim881028** [comment]
> I'm not sure but is it okay to target 94625edf600d36af06d4294c5ec9fe5a10378e18 instead of 38272c46835ba0ab2c7653f634795b5d23e7db45? There are changes like https://github.com/planetarium/lib9c/compare/94625edf600d36af06d4294c5ec9fe5a10378e18..38272c46835ba0ab2c7653f634795b5d23e7db45.

I bumped again, please review again 🙏🏻 @moreal

**Review by moreal — APPROVED** [review]
LGTM! ✅

**Comment by hskim881028** [comment]
Submodule [Lib9c](https://github.com/planetarium/lib9c) updated [0 files](https://github.com/planetarium/lib9c/compare/85b088fab74f9c50f5bb32d5a9748ee7d3c4de61...38272c46835ba0ab2c7653f634795b5d23e7db45).

**Pull request merged**
