### PR TITLE
ci(gh-actions): recover deploy_gh_pages

### PR DESCRIPTION
**Pull request by moreal**
This pull request recovers the `deploy_gh_pages` workflow, removed in #2091, with some bug fixes.

You can try the page at https://moreal.github.io/NineChronicles.Headless/.

## Checkpoints

- [x] To @area363, can we provide `https://9c-internal-rpc-1.nine-chronicles.com/graphql` and `https://9c-main-full-state.nine-chronicles.com/graphql` as the API endpoints? cc @planetarium/devops 
- [x] To @longfin, can we use a graphic logo file from another GPL license project (i.e., `planetarium/9c-launcher`)? cc @Akamig 
- [x] To @longfin, please check the AGPL license notice.

		```
        About AGPL 3.0 license
		
		You MUST UNDERSTAND "HOW AGPL 3.0 LICENSE can affect your application" before using these APIs. When you use these APIs, YOU MUST OPEN YOUR APPLICATION'S SOURCE CODE TO ITS USERS.
		```

## Screenshot

image

### CODE REVIEW

**Comment by area363** [comment]
@moreal https://9c-internal-rpc-1.nine-chronicles.com/graphql is fine but https://9c-main-full-state.nine-chronicles.com/graphql is currently for internal services so could we temporarily use https://9c-main-rpc-1.nine-chronicles.com/graphql?

I'll set up another endpoint that utilizes the full-state-node but includes a WAF protection (something like https://9c-main-api.nine-chronicles.com/graphql) and update it to the page when ready.

**Comment by area363** [comment]
@moreal https://9c-main-api.nine-chronicles.com/graphql is ready 🙏

**Comment by moreal** [comment]
> @moreal [9c-main-api.nine-chronicles.com/graphql](https://9c-main-api.nine-chronicles.com/graphql) is ready 🙏

@area363 I applied it in https://github.com/planetarium/NineChronicles.Headless/compare/12759a925cbf935b3bef1069f8507e5dfa811cdf..de45df8a46376facd9ea14786d6f1f1c81183cf0. Thank you! 🙏🏻

**Comment by area363** [comment]
@moreal Should we wait for @longfin's review? If I approve, the PR will automatically merge 😅

**Comment by moreal** [comment]
@area363 Well I didn't enable `auto-merge` feature for this pull request!

**Comment by area363** [comment]
image
My bad, I thought this meant auto-merge enabled 🤣

**Review by area363 — APPROVED** [review]

**Review by longfin — APPROVED** [review]

**Comment by moreal** [comment]
@longfin Your approval means the above checkpoints are all okay, right?

**Comment by longfin** [comment]
> @longfin Your approval means the above checkpoints are all okay, right?

Yes, I think both are all fine.

**Pull request merged**
